apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    namespace: keycloak
    version: 25.2.0
    releaseName: my-keycloak
