apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - httproute.yaml
  - cluster-issuer.yaml
  - cilium-load-balancer-ip-pool.yaml
  - cilium-network-policy.yaml
  - certificate.yaml