apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - applications/cilium
  # - applications/cert-manager
  - applications/argocd
  # - applications/homepage
  - applications/erpnext
  - applications/actualbudget
  - applications/n8n
  - applications/neo4j
  - applications/openwebui
  - applications/vaultwarden