apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/cilium
  - applications/cert-manager
  - applications/argocd
  # - applications/keycloak
  # - applications/n8n