apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gateway API - Standard CRDs (v1.4.0)
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml

  # Gateway API - TLSRoutes CRD (v1.2.0)
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml

  # Argo CD CRDs (v3.1.9)
  - https://github.com/argoproj/argo-cd/manifests/crds?ref=v3.1.9
