apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - application-set.yaml
  - github.com/global-cloudworks/kubernetes/applications/cilium?ref=main
  - github.com/global-cloudworks/kubernetes/applications/cert-manager?ref=main
  - github.com/global-cloudworks/kubernetes/applications/argocd?ref=main
  - github.com/global-cloudworks/kubernetes/applications/keycloak?ref=main
  - github.com/global-cloudworks/kubernetes/applications/n8n?ref=main
