apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - application-set.yaml
  - https://github.com/global-cloudworks/kubernetes/applications/cilium?ref=main
  - https://github.com/global-cloudworks/kubernetes/applications/argocd?ref=main
