apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - http-route.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    namespace: cert-manager
    version: 1.14.0
    releaseName: cert-manager
    valuesInline:
      crds:
        enabled: true
      installCRDs: true
