apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    namespace: cert-manager
    version: 1.19.1
    releaseName: cert-manager
    valuesInline:
      crds:
        enabled: true
      installCRDs: true
      webhook:
        securePort: 10250
      config:
        apiVersion: controller.config.cert-manager.io/v1alpha1
        kind: ControllerConfiguration
        enableGatewayAPI: true
