apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - gateway-class.yaml
  - cilium-load-balancer-ip-pool.yaml
  - namespace.yaml
  
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.19.0-pre.2
    releaseName: cilium
    valuesInline:
      kubeProxyReplacement: "true"
      gatewayAPI:
        enabled: true
      k8sServiceHost: 10.128.15.231
      k8sServicePort: 6443
      operator:
        replicas: 1
      encryption:
        enabled: true
        type: wireguard
