apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.18.1
    releaseName: cilium
    valuesInline:
      gatewayAPI:
        enabled: true
      kubeProxyReplacement: true
      k8sServiceHost: "localhost"
      k8sServicePort: "6443"
      operator:
        replicas: 1
        tollerations:
          - key: "CriticalAddonsOnly"
            operator: Exists
            effect: "NoExecute"
      encryption:
        enabled: true
        type: wireguard
      hubble:
        enabled: true
        relay:
          enabled: true
        ui:
          enabled: true
      envoy:
        enabled: true
        tollerations:
          - key: "CriticalAddonsOnly"
            operator: Exists
            effect: "NoExecute"
        securityContext:
          capabilities:
            keepCapNetBindService: true


          