apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - gateway-class.yaml
  - cilium-load-balancer-ip-pool.yaml
  - cilium-network-policy.yaml
  - namespace.yaml
  
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.19.0
    releaseName: cilium
    valuesInline:
      routing-mode: native
      ipam: kubernetes
      ipv4-native-routing-cidr: 10.128.0.0/20
      auto-direct-node-routes: true
      bpf:
        masquerade: true
        lbExternalClusterIP: true
      kubeProxyReplacement: true
      gatewayAPI:
        enabled: true
      k8sServiceHost: 10.128.15.231
      k8sServicePort: 6443
      operator:
        replicas: 1
      encryption:
        enabled: true
        type: wireguard
      hubble:
        enabled: true
        relay:
          enabled: true
        ui:
          enabled: true