apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml
  - cilium-load-balencer-ip-pool.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.18.1
    releaseName: cilium
    valuesInline:
      gatewayAPI:
        enabled: true
      kubeProxyReplacement: true
      k8sServiceHost: "localhost"
      k8sServicePort: "6443"
      l2announcements:
        enabled: true 
        leaseDuration: 10s
        leaseRenewDeadline: 5s
        leaseRetryPeriod: 1s
      defaultLBServiceIPAM: "lbipam"
      operator:
        replicas: 1
      encryption:
        enabled: true
        type: wireguard
      hubble:
        enabled: true
        relay:
          enabled: true
        ui:
          enabled: true
      envoy:
        enabled: true
        securityContext:
          capabilities:
            keepCapNetBindService: true