apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.18.2
    releaseName: cilium
    valuesFile: values.yaml