apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.18.1
    releaseName: cilium
    valuesInline:
      gatewayAPI:
        enabled: true
      kubeProxyReplacement: "true"
      operator:
        replicas: 1
      encryption:
        enabled: true
        type: wireguard