apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - gateway-class.yaml
  - cilium-load-balancer-ip-pool.yaml
  - cilium-network-policy.yaml
  - namespace.yaml
  
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    version: 1.18.1
    releaseName: cilium
    valuesInline:
      kubeProxyReplacement: false
      gatewayAPI:
        enabled: true
      k8sServiceHost: localhost
      k8sServicePort: 6443
      operator:
        replicas: 1
      encryption:
        enabled: true
        type: wireguard
      hubble:
        enabled: true
        relay:
          enabled: true
        ui:
          enabled: true
      ipam:
        mode: kubernetes
      bpf:
        mapDynamicSize: true
      kube-proxy:
        service-cluster-ip-range: 10.43.0.0/16
      kubernetes:
        service-cidr: 10.43.0.0/16
      nodeinit:
        enabled: true
      hostServices:
        enabled: true