apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: erpnext
    repo: https://helm.erpnext.com
    namespace: default
    version: 7.0.247
    releaseName: my-erpnext
    valuesInline:
