node-iface: cilium_host
node-name: cloud-proxy
tls-san:
  - ${EXTERNAL_IP}
cni: none
disable-kube-proxy: true
disable:
  - rke2-ingress-nginx
write-kubeconfig-mode: "0600"
cni-conf-dir: /etc/cni/net.d
cni-bin-dir: /opt/cni/bin