node-ip: ${INTERNAL_IP}
node-name: ${INTERNAL_IP}
advertise-address: ${INTERNAL_IP}
node-external-ip: ${INTERNAL_IP}
tls-san:
  - ${EXTERNAL_IP}
cni: none
disable-kube-proxy: true
disable:
  - rke2-ingress-nginx
write-kubeconfig-mode: "0600"
cni-conf-dir: /etc/cni/net.d
cni-bin-dir: /opt/cni/bin
kube-apiserver-arg:
  - "secure-port=6444"