apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml
  - secret.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    version: 8.2.7
    releaseName: argocd
    valuesInline:

