apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
  - name: neo4j
    repo: https://neo4j.github.io/helm-charts/
    namespace: neo4j
    version: 2025.9.0
    releaseName: neo4j
    valuesInline:
