apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-deployment
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: 
  - "missingkey=error"
  generators:
  - git:
      repoURL: https://github.com/global-cloudwork/kubernetes.git
      revision: main
      directories:
      - path: applications/**/
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/global-cloudwork/kubernetes.git
          targetRevision: main
          path: '{{ .path }}'
          kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .name }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true