apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - namespace.yaml
  
helmCharts:
  - name: 
    repo: 
    namespace: k
    version: 
    releaseName: 
    valuesInline:
