apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    namespace: n8n
    version: 1.15.17
    releaseName: n8n
