apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - application-set.yaml
  - edge/cluster-issuer.yaml
  - edge/gateway.yaml
  - edge/httproute.yaml
  - edge/network-policy