apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vaultwarden
    repo: https://gissilabs.github.io/charts
    namespace: vaultwarden
    version: 1.2.6
    valuesFile: values.yaml
    releaseName: my-vaultwarden
