node-name: cloud-proxy
cni: none
disable-kube-proxy: true
tls-san:
  - ${EXTERNAL_IP}
disable:
  - rke2-ingress-nginx
write-kubeconfig-mode: "0600"
cloud-provider-name: "gce"
server-arg:
  - "--bind-address=0.0.0.0"
kubelet-arg:
  - 'register-with-taints=node.cilium.io/agent-not-ready:NoExecute'

rancher_kubernetes_engine_config:
  cloud_provider:
    name: gce
    customCloudProvider: |-
      [Global]
      project-id=global-cloudworks
      network-name=default
      subnetwork-name=us-central1
      node-instance-prefix=development
      node-tags=http-server,https-server
  services:
    kube_controller:
      extra_args:
        configure-cloud-routes: true