node-name: cloud-proxy
cni: none
disable-kube-proxy: true
node-ip: ${INTERNAL_IP}
advertise-address: ${INTERNAL_IP}
bind-address: 172.0.0.1
tls-san:
  - ${EXTERNAL_IP}
disable:
  - rke2-ingress-nginx
write-kubeconfig-mode: "0600"