node-name: cloud-proxy
cni: none
disable-kube-proxy: true
tls-san:
  - ${EXTERNAL_IP}
disable:
  - rke2-ingress-nginx
write-kubeconfig-mode: "0600"
kubelet-arg:
  - 'register-with-taints=node.cilium.io/agent-not-ready:NoExecute'
cloud-provider-name: external
cloud-provider-config: "/etc/rancher/rke2/cloud.conf"