node-name: cloud-proxy
tls-san:
  - ${EXTERNAL_IP}
cni: none
disable-kube-proxy: true
disable:
  - rke2-cilium
  - rke2-ingress-nginx
write-kubeconfig-mode: "0600"
cluster-cidr: 10.42.0.0/16
service-cidr: 10.43.0.0/16